---
title: "Silhouette toy example"
output: html_document
date: "2023-09-10"
---

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
})
knitr::opts_chunk$set(dev="CairoPNG")
# source("../../../ClusteringMetrics/R/CDbw.R")
devtools::load_all("../../../ClusteringMetrics")
```

```{r}
makeSwData <- function(sd1=3, offset1=-4, sd2=0.6, constantY1=FALSE, seed=1){
  set.seed(seed)
  d1 <- data.frame(x=rnorm(50, offset1, sd=sd1), y=0, class="A")
  if(constantY1){
    d1$y <- rnorm(50, 0.3*sd1)
  }else{
    d1$y <- rnorm(50, 4+d1$x)
  }
  ggplot(d1, aes(x,y)) + geom_point()
  d2 <- data.frame(x=rnorm(20, 3.5, sd=0.6), y=rnorm(20, sd=sd2), class="B")
  d <- rbind(d1,d2)
  d$sw <- cluster::silhouette(as.integer(factor(d$class)), dist(d[,1:2]))[,3]
  d
}

da <- makeSwData(seed=10)
```

```{r}
d3 <- d2 <- makeSwData(sd1=2.5, offset1=-3, seed=24, sd2=0.7, constantY1 = TRUE)
# we make some adjustments to the random data to get the desired silhouettes:
w <- which(d3$class=="A")
d3$x[w] <- d3$x[w]+0.7
d3$x[head(order(d3$sw),3)] <- d3$x[head(order(d3$sw),3)]-1
d3$y[head(order(d3$sw),3)] <- d3$y[head(order(d3$sw),3)] - (d3$y[head(order(d3$sw),3)]-0.3)/2
# recompute silhouettes
d3$sw <- cluster::silhouette(as.integer(factor(d3$class)), dist(d3[,1:2]))[,3]
getGlobal <- function(d){
  a <- CDbw(d[,1:2], as.integer(factor(d$class)))
  names(a) <- paste0("CDbw\n",gsub("^sep$","separation",names(a)))
  a <- c(a, "mean\nsilh.width"=mean(d$sw))
  a <- c(a, "DBCV"=getEmbeddingGlobalMetrics(d[,1:2], as.integer(factor(d$class)), metrics = c("dbcv")))
  return(a)
}
gm <- getGlobal(da)
gm <- data.frame(scenario=rep(as.character(1:2), each=6),
                 metric=rep(names(gm),2),
                 value=unlist(c(gm, getGlobal(d3))))
gmp <- gm %>% mutate(metric = recode(metric, "CDbw\ncdbw"="CDbw", "DBCV.dbcv"="DBCV")) %>%
ggplot(aes(x=scenario, y=value, fill=scenario)) +
  geom_col(position = "dodge") + facet_wrap(~metric, scales="free_y", ncol=2) + 
  theme_bw() + theme(legend.position="bottom", axis.title.x=element_blank(),
                          legend.justification=c(1, 0),
                          axis.text.x=element_blank(),
                          axis.ticks.x=element_blank(),
                          plot.margin = margin(1, 1, 0, 0), 
                          legend.box.spacing = unit(-0.05, "cm"),
                          strip.background=element_blank())
```


```{r}
swPlot <- function(d3, title=NULL, lims=c(-0.206,0.92)){
  sw <- ggplot(d3, aes(sw)) + geom_histogram(fill="darkblue") + theme_classic() + 
    labs(x="Silhouette width") + coord_cartesian(xlim=lims) +
    geom_vline(xintercept=mean(d3$sw)) + scale_y_continuous(breaks=scales::pretty_breaks(n = 4))
  if(!is.null(title)) sw <- sw + ggtitle(title)
  sw
}
pPlot <- function(d3, lims=c(-0.206,0.92)){
  ag <- aggregate(d3[,c("x","y")], by=d3[,"class",drop=FALSE], FUN=mean)
  ggplot(d3, aes(x,y, shape=class, colour=sw)) + geom_point(size=3.5) +
    scale_color_gradient2(low="red", mid="darkgrey", high="blue", midpoint = 0, limits=lims) + 
    theme_classic() + labs(color="Silhouette width ") + theme(legend.position = "bottom") #+
    #geom_point(data=ag, colour="black", size=3.5)
}
```


```{r, fig.width=8.5, fig.height=4.5}
p1 <- (((swPlot(da, "Scenario 1") + swPlot(d3, "Scenario 2")) / (pPlot(da) + pPlot(d3))) + 
  plot_layout(guides = "collect", heights = c(1,3)) & theme(legend.position = "bottom"))
pdf("SW.pdf", width=8.5, height=4.5)
 cowplot::plot_grid(p1, gmp, rel_widths=c(1,0.42), labels=letters[1:2], scale=c(0.95, 1))
dev.off()
```
