```{r}
suppressPackageStartupMessages({
    library(ggplot2)
    library(patchwork)
    library(dplyr)
  library(parallel)
  library(cowplot)
  })
```

```{r}
devtools::load_all("~/public/SiyuanLuo/projects/clustering_metrics/ClusteringMetrics")
```

```{r}
moon_maker <- function(n = 50, noise = 0.1,
                         x_center = 0, y_center = 0, radius = 1, seed=42) {
    set.seed(seed)
    moon <- tibble(
      i = 1:n,
      x = x_center + radius * cos(pi * i/n) + rnorm(n, 0, sd = noise * radius),
      y = y_center + radius * sin(pi * i/n) + rnorm(n, 0, sd = noise * radius),
    )
    return(data.frame(moon))
  }
```

```{r}
# Combine the data into a data frame for easier manipulation
df1 <- moon_maker(n = 100, x_center = 1, y_center = -1)
df1$label = 1
df2 <- moon_maker(n = 100, x_center = 2, y_center = 0.5)
df2$label = 2
df2$y <- - df2$y
data <- rbind(df1, df2)
data$label <- as.factor(data$label)
noisy_moon <- data[, c("x", "y", "label")]

# Perform K-means clustering
kmeans_result <- kmeans(data, centers = 2)
kmeans_labels <- kmeans_result$cluster
noisy_moon$kmeans_label <- factor(kmeans_labels)

# Perform HDBSCAN clustering
library(dbscan)
hdbscan_result <- hdbscan(as.matrix(data[,c("x", "y")]), minPts = 5)
hdbscan_labels <- hdbscan_result$cluster
noisy_moon$hdbscan_label <- factor(hdbscan_labels)
data <- noisy_moon
```

```{r}
p1 <- ggplot(data, aes(x, y, color=kmeans_label)) + 
  geom_point() +
  theme_bw() + 
  labs(color="kmeans cluster", x="", y="") + 
  scale_color_brewer(palette = "Set1") + 
  theme(plot.margin = margin(1, 1, 0, 0), 
        legend.position = "bottom",
        legend.box.spacing = unit(-0.5, "cm"))

p2 <- ggplot(data, aes(x, y, color=hdbscan_label)) + 
  geom_point() +
  theme_bw() + labs(color="HDBSCAN cluster", x="", y="") + 
  scale_color_brewer(palette = "Set1") + 
  theme(plot.margin = margin(1, 1, 0, 0), 
        legend.position = "bottom",
        legend.box.spacing = unit(-0.5, "cm"))
```

```{r}
library(tidyr)
res1 <- getEmbeddingGlobalMetrics(data[,c("x","y")], data$kmeans_label)
res2 <- getEmbeddingGlobalMetrics(data[,c("x","y")], data$hdbscan_label)
res1 <- pivot_longer(res1, cols = colnames(res1), names_to = "metric")
res1$scenario <- "A"
res2 <- pivot_longer(res2, cols = colnames(res2), names_to = "metric")
res2$scenario <- "B"
df <- rbind(res1, res2) %>% 
   mutate(metric = recode(metric, 
                          "meanSW" = "mean silh.width", 
                          "cdbw" = "CDbw", 
                          "cohesion" = "CDbw cohesion",
                          "sep" = "CDbw separation",
                          "compactness" = "CDbw compactness",
                          "dbcv" = "DBCV")) %>% 
  filter (metric %in% c("mean silh.width", "CDbw", "CDbw cohesion", "CDbw separation", "CDbw compactness", "DBCV")) 
df$metric<- gsub(" ", "\n", df$metric)

p3 <- df %>% 
  ggplot(aes(x=scenario, y=value, fill=scenario)) + 
  geom_col(position = "dodge") + theme_bw() + 
  facet_wrap(~metric, nrow = 3, scales = "free_y") + theme_bw() +
  theme(plot.margin = margin(1, 1, 0, 0), 
        legend.position = "bottom",
        strip.background=element_blank(),
        legend.box.spacing = unit(-0.1, "cm"),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  labs(fill="scenario", x="", y="")
```


```{r}
pdf(file="convexity.pdf", width=7, height=5)
# cowplot::plot_grid(p1 + theme(legend.box.margin=unit(0.26, "cm")), 
#                    p2 + theme(legend.box.margin=unit(0, "cm")), 
#                    p3,  
#                    labels=LETTERS[1:3], nrow=3)
col_plot <- plot_grid(p1, p2, labels=LETTERS[1:2], ncol = 1)
final_plot <- plot_grid(col_plot, p3, nrow = 1, labels=c("", "C"), rel_widths = c(1, 0.6))
final_plot
dev.off()
```


```{r}
# cowplot::plot_grid(p1, 
#                    p2, 
#                    p3,  
#                    labels=LETTERS[1:3], nrow=3)
```



