---
title: "Silhouette toy example and the noisy moon toy example"
output: html_document
date: "2023-09-10"
---

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
  library(dplyr)
  library(parallel)
  library(cowplot)
})
knitr::opts_chunk$set(dev="CairoPNG")
# source("../../../ClusteringMetrics/R/CDbw.R")
devtools::load_all("../../../ClusteringMetrics")
```
# Silhouette dataset
```{r}
makeSwData <- function(sd1=3, offset1=-4, sd2=0.6, constantY1=FALSE, seed=1){
  set.seed(seed)
  d1 <- data.frame(x=rnorm(50, offset1, sd=sd1), y=0, class="A")
  if(constantY1){
    d1$y <- rnorm(50, 0.3*sd1)
  }else{
    d1$y <- rnorm(50, 4+d1$x)
  }
  ggplot(d1, aes(x,y)) + geom_point()
  d2 <- data.frame(x=rnorm(20, 3.5, sd=0.6), y=rnorm(20, sd=sd2), class="B")
  d <- rbind(d1,d2)
  d$sw <- cluster::silhouette(as.integer(factor(d$class)), dist(d[,1:2]))[,3]
  d
}

da <- makeSwData(seed=10)
```

```{r}
d3 <- d2 <- makeSwData(sd1=2.5, offset1=-3, seed=24, sd2=0.7, constantY1 = TRUE)
# we make some adjustments to the random data to get the desired silhouettes:
w <- which(d3$class=="A")
d3$x[w] <- d3$x[w]+0.7
d3$x[head(order(d3$sw),3)] <- d3$x[head(order(d3$sw),3)]-1
d3$y[head(order(d3$sw),3)] <- d3$y[head(order(d3$sw),3)] - (d3$y[head(order(d3$sw),3)]-0.3)/2
# recompute silhouettes
d3$sw <- cluster::silhouette(as.integer(factor(d3$class)), dist(d3[,1:2]))[,3]
getGlobal <- function(d){
  a <- CDbw(d[,1:2], as.integer(factor(d$class)))
  names(a) <- paste0("CDbw\n",gsub("^sep$","separation",names(a)))
  a <- c(a, "mean\nsilh.width"=mean(d$sw))
  a <- c(a, "DBCV"=getEmbeddingGlobalMetrics(d[,1:2], as.integer(factor(d$class)), metrics = c("dbcv")))
  return(a)
}
gm <- getGlobal(da)
gm <- data.frame(scenario=rep(as.character(1:2), each=6),
                 metric=rep(names(gm),2),
                 value=unlist(c(gm, getGlobal(d3))))
gmp <- gm %>% mutate(metric = recode(metric, "CDbw\ncdbw"="CDbw", "DBCV.dbcv"="DBCV")) %>%
ggplot(aes(x=scenario, y=value, fill=scenario)) + labs(y="") +
  geom_col(position = "dodge") + facet_wrap(~metric, scales="free_y", ncol=2) + 
  theme_bw() + theme(legend.position="bottom", axis.title.x=element_blank(),
                          legend.justification=c(1, 0),
                          axis.text.x=element_blank(),
                          axis.ticks.x=element_blank(),
                          plot.margin = margin(1, 1, 0, 0), 
                          legend.box.spacing = unit(-0.05, "cm"),
                          strip.background=element_blank())

```

```{r}
swPlot <- function(d3, title=NULL, lims=c(-0.206,0.92)){
  sw <- ggplot(d3, aes(sw)) + geom_histogram(fill="darkblue") + theme_classic() + 
    labs(x="Silhouette width") + coord_cartesian(xlim=lims) +
    geom_vline(xintercept=mean(d3$sw)) + scale_y_continuous(breaks=scales::pretty_breaks(n = 4))
  if(!is.null(title)) sw <- sw + ggtitle(title)
  sw
}
pPlot <- function(d3, lims=c(-0.206,0.92)){
  ag <- aggregate(d3[,c("x","y")], by=d3[,"class",drop=FALSE], FUN=mean)
  ggplot(d3, aes(x,y, shape=class, colour=sw)) + geom_point(size=3.5) +
    scale_color_gradient2(low="red", mid="darkgrey", high="blue", midpoint = 0, limits=lims) + 
    theme_classic() + labs(color="Silhouette width ") + theme(legend.position = "bottom") #+
    #geom_point(data=ag, colour="black", size=3.5)
}
```


# Noisy moon dataset
```{r}
moon_maker <- function(n = 50, noise = 0.1,
                         x_center = 0, y_center = 0, radius = 1, seed=42) {
    set.seed(seed)
    moon <- tibble(
      i = 1:n,
      x = x_center + radius * cos(pi * i/n) + rnorm(n, 0, sd = noise * radius),
      y = y_center + radius * sin(pi * i/n) + rnorm(n, 0, sd = noise * radius),
    )
    return(data.frame(moon))
  }
```

```{r}
# Combine the data into a data frame for easier manipulation
df1 <- moon_maker(n = 100, x_center = 1, y_center = -1)
df1$label = 1
df2 <- moon_maker(n = 100, x_center = 2, y_center = 0.5)
df2$label = 2
df2$y <- - df2$y
data <- rbind(df1, df2)
data$label <- as.factor(data$label)
noisy_moon <- data[, c("x", "y", "label")]

# Perform K-means clustering
kmeans_result <- kmeans(data, centers = 2)
kmeans_labels <- kmeans_result$cluster
noisy_moon$kmeans_label <- factor(kmeans_labels)

# Perform HDBSCAN clustering
library(dbscan)
hdbscan_result <- hdbscan(as.matrix(data[,c("x", "y")]), minPts = 5)
hdbscan_labels <- hdbscan_result$cluster
noisy_moon$hdbscan_label <- factor(hdbscan_labels)
data <- noisy_moon
```

```{r}
p2 <- ggplot(data, aes(x, y, color=kmeans_label)) + 
  geom_point() +
  theme_bw() + 
  labs(color="kmeans cluster", x="", y="") + 
  scale_color_brewer(palette = "Set1") + 
  theme(plot.margin = margin(5, 30, 0, 10), 
        legend.position = "bottom",
        legend.box.spacing = unit(-0.5, "cm")) +
  labs(title="Scenario 3")

p3 <- ggplot(data, aes(x, y, color=hdbscan_label)) + 
  geom_point() +
  theme_bw() + labs(color="HDBSCAN cluster", x="", y="") + 
  scale_color_brewer(palette = "Set1") + 
  theme(plot.margin = margin(5, 30, 0, 10), 
        legend.position = "bottom",
        legend.box.spacing = unit(-0.5, "cm")) +
    labs(title="Scenario 4")
```

```{r}
library(tidyr)
res1 <- getEmbeddingGlobalMetrics(data[,c("x","y")], data$kmeans_label)
res2 <- getEmbeddingGlobalMetrics(data[,c("x","y")], data$hdbscan_label)
res1 <- pivot_longer(res1, cols = colnames(res1), names_to = "metric")
res1$scenario <- "3"
res2 <- pivot_longer(res2, cols = colnames(res2), names_to = "metric")
res2$scenario <- "4"
df <- rbind(res1, res2) %>% 
   mutate(metric = recode(metric, 
                          "meanSW" = "mean silh.width", 
                          "cdbw" = "CDbw", 
                          "cohesion" = "CDbw cohesion",
                          "sep" = "CDbw separation",
                          "compactness" = "CDbw compactness",
                          "dbcv" = "DBCV")) %>% 
  filter (metric %in% c("mean silh.width", "CDbw", "CDbw cohesion", "CDbw separation", "CDbw compactness", "DBCV")) 
df$metric<- gsub(" ", "\n", df$metric)

p4 <- df %>% 
  ggplot(aes(x=scenario, y=value, fill=scenario)) + 
  geom_col(position = "dodge") + theme_bw() + 
  facet_wrap(~metric, nrow = 3, scales = "free_y") + theme_bw() +
  theme(plot.margin = margin(1, 1, 0, 0), 
        legend.position = "bottom",
        strip.background=element_blank(),
        legend.box.spacing = unit(-0.1, "cm"),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  labs(fill="scenario", x="", y="")
```


```{r}
col_plot <- plot_grid(p2, p3, labels=c("c", ""), ncol = 1)
p5 <- plot_grid(col_plot, p4, nrow = 1, labels=c("", "d"), rel_widths = c(1, 0.5))
```


```{r, fig.width=8.5, fig.height=4.5}
p1 <- (((swPlot(da, "Scenario 1") + swPlot(d3, "Scenario 2")) / (pPlot(da) + pPlot(d3))) + 
  plot_layout(guides = "collect", heights = c(1,3)) & theme(legend.position = "bottom"))

pdf("embedding_toy_example.pdf", width=8, height=9)
 p6 <- cowplot::plot_grid(p1, gmp, rel_widths=c(1,0.5), labels=letters[1:2], scale=c(0.95, 1))
 cowplot::plot_grid(p6, p5, nrow=2, rel_heights=c(1,1))
dev.off()
```


```{r}
re <- data.frame(matrix(nrow = 0, ncol=6))
for (r in c(10, 15, 20, 30, 40, 50, 60, 70, 80, 90)) {
  re <- rbind(re, data.frame(r=r, method="kmeans", t(CDbw(data[,c("x","y")], as.integer(data$kmeans_label), r=r))))
  re <- rbind(re, data.frame(r=r, method="HDBSCAN", t(CDbw(data[,c("x","y")], as.integer(data$hdbscan_label), r=r))))
}

re_long <- pivot_longer(re, cols = setdiff(colnames(re), c("r","method")), names_to = "metric")
df <- re_long %>% 
   mutate(metric = recode(metric, 
                          "cdbw" = "CDbw", 
                          "cohesion" = "CDbw cohesion",
                          "sep" = "CDbw separation",
                          "compactness" = "CDbw compactness",
                          "dbcv" = "DBCV")) 

df$metric<- gsub(" ", "\n", df$metric)

ps <- df %>% 
  ggplot(aes(x=r, y=value, color=method, group=method)) + 
  geom_point() + theme_bw() + geom_line() +
  facet_wrap(~metric, scales = "free_y") + theme_bw() +
  theme(plot.margin = margin(1, 1, 0, 0), 
        legend.position = "bottom",
        strip.background=element_blank(),
        legend.box.spacing = unit(0, "cm")) + 
  labs(color="Method", x="Number of representatives", y="")
ps
```

```{r}
pdf("cdbw_r.pdf", width=6, height=4)
ps
dev.off()
```

```{r}

```

