---
title: "Measure clustering properties across simulations"
output: html_document
date: "2024-08-13"
---

```{r}
suppressPackageStartupMessages({
  library(BiocParallel)
})
knitr::opts_chunk$set(dev="CairoPNG")
devtools::load_all("../../ClusteringMetrics/")
```

```{r}
g <- expand.grid(Ns=c("100,100,100","200,100,50","300,60,20","100,30,600","300,50,50,50","100,100,100,100"),
                 classDiff=c("1,2,2","1,1,1","0,1,2","1,1,2","0.5,0.5,2","1,1,1,1,1,1","1,1,2,2,1,2","2,3,1","2,2,3"),
                 Sds=c(0.5,1,2,"1,2,1"), ndims=c(2,3),
                 spread=c("1,2,1","1,1,1","2,1,2","3,2,1","1,1,2,1","1,1,4"))
gi <- apply(g,2,FUN=function(x) lengths(strsplit(x,",")))
w <- which(gi[,5]==gi[,1] & (gi[,3]==1 | gi[,3]==gi[,1]) &
               gi[,2]==gi[,1] & g[,4]<=(gi[,1]-1))
g <- g[w,]
gi <- gi[w,]
saveRDS(g, "simParams.rds")
set.seed(123)
sims <- lapply(seq_len(nrow(g)),FUN=function(i){
  mockData(as.numeric(strsplit(as.character(g[i,1]),",")[[1]]),
            classDiff=as.numeric(strsplit(as.character(g[i,2]),",")[[1]]),
            Sds=as.numeric(strsplit(as.character(g[i,3]),",")[[1]]),
            ndims=g[i,4],
            spread=as.numeric(strsplit(as.character(g[i,5]),",")[[1]]))
  
})
saveRDS(g, "simulations.rds")
```

```{r}
mets <- dplyr::bind_rows(bplapply(sims, BPPARAM=MulticoreParam(3, progress=FALSE), FUN=function(x){
  gm <- ClusteringMetrics::getGraphClassMetrics(x[,-ncol(x)], x[,ncol(x)], k=5)
  gm$class <- levels(x$class)
  gm
}), .id="simulation")
saveRDS(mets, "sim_metrics.rds")
cc <- cor(as.matrix(mets[,c(-1,-ncol(mets))]))
cc.sp <- cor(as.matrix(mets[,c(-1,-ncol(mets))]), method="spearman")
ComplexHeatmap::Heatmap(cc, name="Pearson") + ComplexHeatmap::Heatmap(cc.sp, name="Spearman")
```


```{r}
sessionInfo()
```

