---
title: "Spatial image data"
output: html_document
date: "2025-05-27"
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
library(tidyr)
library(cowplot)
library(dplyr)
library(ComplexHeatmap)
library(ggokabeito)
# library(poem)
devtools::load_all("~/public/SiyuanLuo/projects/clustering_metrics/poem")
library(RColorBrewer)
library(pals)
library(ggpubr)
my_col_polychrome <- as.vector(unlist(polychrome()))
```

```{r, eval=FALSE}
# code to organize the data
method_ls <- c("BANKSY", "bass", "CellCharter", "DRSC", "precast", "scanpy", "SEDR", "seurat", "SpaceFlow", "spaGCN", "STAGATE", "SCAN-IT")
df <- read.table("../../data/spatial_real_data/STARmap_plus/well11/coordinates.tsv", sep='\t', header=TRUE)
colnames(df) <- c("id", "x", "y", "z")

labels <- read.table("../../data/spatial_real_data/STARmap_plus/well11/labels.tsv", sep='\t', header=TRUE)
labels <- rename(labels, id = "X")
df <- merge(df, labels, by="id")

for (method in method_ls) {
  tmp <- read.table(paste0("../../data/spatial_real_data/STARmap_plus/well11/", method, "/config_default/domains.tsv") , sep='\t', header=TRUE)
  tmp$label <- factor(tmp$label)
  colnames(tmp) <- c("id", method)
  df <- merge(df, tmp, by="id")
}

write.table(df, file="../../data/spatial_real_data/STARmap_plus/well11_all_results.tsv", sep='\t', row.names=FALSE, quote=FALSE)
```

```{r}
s <- 0.1

df$domain_annotation <- gsub("^VS_\\d+$", "VS", df$Sub_molecular_tissue_region)
  # ifelse(grepl("^VS(_\\d+)?$", df$Sub_molecular_tissue_region), "VS", "others")
df$domain_annotation <- gsub("^TH_\\d+$", "TH", df$domain_annotation)
df$domain_annotation <- gsub("^CNU_\\d+$", "CNU", df$domain_annotation)
df$domain_annotation <- gsub("^HY_\\d+$", "HY", df$domain_annotation)
df$domain_annotation <- gsub("^FT_\\d+$", "FT", df$domain_annotation)
df$domain_annotation <- gsub("^MB_P_MY_\\d+$", "MB_P_MY", df$domain_annotation)
df$domain_annotation <- gsub("^CTX_A_\\d+$", "CTX_A", df$domain_annotation)
df$domain_annotation <- gsub("^CTX_B_\\d+$", "CTX_B", df$domain_annotation)
df$domain_annotation <- gsub("^CTX_HIP_\\d+$", "CTX_HIP", df$domain_annotation)

okabe_ito_extended <- c(
  "#F0E442", "#E69F00",  "#000000", "#56B4E9", 
  "#009E73", "#D55E00", "#999999", "#CC79A7", 
  "#0072B2",   # black (already reasonably distinct)
  "#6A5ACD"   # white or a custom color depending on your background
)

p0 <- ggplot(df) +
    geom_point(aes(x = y, y = -x, color=domain_annotation), size = s) +
    labs(x = "", y = "", color="", title="Manual annotation") +
    theme_minimal()  +
    scale_color_manual(values=okabe_ito_extended) +
  theme(
  legend.box = "horizontal",
  legend.box.background = element_rect(fill = "grey90", color = "black", size = 0.1),
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  axis.title.x=element_blank(),
  legend.justification=c(0, 0),
  legend.position = "bottom",
  legend.box.spacing = margin(0),
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(-0.5, "cm"),
  panel.grid.major = element_blank(), 
  panel.grid.minor = element_blank(),
  plot.title = element_text(hjust = 0.5, size=10)) +
  guides(
    color = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3)), 
    fill = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3))
  )


selected_mt <- c("CellCharter","scanpy")
df$CellCharter <- df$CellCharter %>% recode("1" = "0",
                                      "2" = "1",
                                      "0" = "2",
                                      "6" = "5",
                                      "4" = "6",
                                      "5" = "4")
dfl <- df %>% select(id, x, y, all_of(selected_mt)) %>%
  pivot_longer(cols = all_of(selected_mt), names_to = "label_type", values_to = "Prediction")

p1 <- ggplot(dfl) +
    geom_point(aes(x = y, y = -x, color=Prediction), size = s) +
  facet_wrap(~ label_type, ncol=2) +  # Creates a separate plot for each label_type
  labs(x = "", y = "", color="Prediction") +
  theme_minimal() +
  scale_color_okabe_ito(order=c(6,7,1,5,3,4,2)) +
  theme(
  # legend.position=c(1.08, 0.1),
  legend.box = "horizontal",
  legend.box.background = element_rect(fill = "grey90", color = "black", size = 0.1),
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  # legend.spacing.x = unit(-0.2, "cm"),
  axis.title.x=element_blank(),
  # legend.justification=c(0, 0),
  legend.position = "bottom",
  legend.box.spacing = margin(0),
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(0.5, "cm"),
  panel.grid.major = element_blank(), 
  panel.grid.minor = element_blank(),
  plot.title = element_text(hjust = 0.5, size=10)
) +
  guides(
    color = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3)), 
    fill = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3))
  )
```

```{r}
p1.1 <- cowplot::plot_grid(p0, p1, ncol=2, rel_widths =c(1.05, 2), labels=c("",""))
```

```{r}
methods <- selected_mt

partition_metrics <- c("ARI","AWC","AWH")
true <- factor(df$domain_annotation)

res <- data.frame(matrix(ncol = length(partition_metrics) + 1, nrow = 0))
colnames(res) <- c("method", partition_metrics)
for (mt in methods) {
  pred <- factor(df[, mt])
  res <- rbind(res, data.frame(method=mt, getPartitionMetrics(true, pred, metrics=partition_metrics, level="dataset")))
}

spatial_ex_metrics <- c("nsARI","nsAWH", "nsAWC","nsAccuracy", "SpatialARI")
res2 <- data.frame(matrix(ncol = length(spatial_ex_metrics) + 1, nrow = 0))
colnames(res2) <- c("method", spatial_ex_metrics)
for (mt in methods) {
  pred <- factor(df[, mt])
  res2 <- rbind(res2, data.frame(method=mt, getSpatialExternalMetrics(true=true, pred=pred, location=df[, c("x","y")], level="dataset", metrics=spatial_ex_metrics, lowMemory=TRUE)))
}

spatial_in_metrics <- c("PAS", "ELSA", "CHAOS")
res3 <- data.frame(matrix(ncol = length(spatial_in_metrics) + 1, nrow = 0))
colnames(res3) <- c("method", spatial_in_metrics)
for (mt in methods) {
  pred <- factor(df[, mt])
  res3 <- rbind(res3, data.frame(method=mt, getSpatialInternalMetrics(labels=pred, location=df[, c("x","y")], k=6, level="dataset", metrics=spatial_in_metrics)))
}

res <- merge(res, res2, by="method")
res <- merge(res, res3, by="method")
res <- res %>% pivot_longer(cols = -method, names_to = "metric", values_to = "value")
saveRDS(res, file="../../data/spatial_real_data/STARmap_plus/well11_metric_results.RDS")
```

```{r}
res <- res[!(res$metric %in% c("ELSA.Ea", "ELSA.Ec")), ]
res$metric <- factor(res$metric, levels=c(
  "ARI", "AWC", "AWH", 
  "nsARI", "nsAWH", "nsAWC", "nsAccuracy", "SpatialARI",
  "PAS", "ELSA", "CHAOS"
))
res$metric_type <- rep(c(rep("Partition", 3), 
                     rep("Spatial External", 5), 
                     rep("Spatial Internal", 3)),2)
  
p2 <- res %>%
  ggplot(aes(metric, value, group=method, color=method, shape=metric_type)) +
  geom_point(size=4) + 
  # geom_line(size=0.8) +
  scale_color_okabe_ito() +
  theme_bw() + ylim(0, 0.65) +
  labs(x="Metric", y="Value", color="Method", shape="Metric Category") +
  theme(legend.position = "bottom",
        legend.margin = margin(t = -5),  # Increase top margin of legend (space above it)
    plot.margin = margin(0, 5, 0, 5)  # top, right, bottom, left margins around plot
    )
p2
```

```{r}
pdf("spatial_image_data.pdf", width=8, height=6)
cowplot::plot_grid(p1.1, p2, ncol=1, rel_heights=c(0.6, 0.3), labels=c("a","b"))
dev.off()
```

