---
title: "Spatial real data"
output: html_document
date: "2024-05-23"
---

```{r}
library(ggplot2)
library(tidyr)
library(cowplot)
library(dplyr)
library(ComplexHeatmap)
library(ggokabeito)
devtools::load_all("~/public/SiyuanLuo/projects/clustering_metrics/ClusteringMetrics")
```

```{r}
df <- readRDS(file="../../spatial_real_data/obs_Br8100_151673_spe_coldata.RDS")
```

```{r}
df$ground_truth_label <- df$ground_truth_recode %>% recode("1" = "1",
                                                           "2" = "1",
                                                           "5" = "1",
                                                           "3" = "1",
                                                           "4" = "0",
                                                           "6" = "0",
                                                           "7" = "0")

dfl <- pivot_longer(df, cols = contains("default") | contains("ground_truth_recode"), 
             names_to = "label_type", values_to = "prediction") 
dfl$label_type <- factor(dfl$label_type, levels=c("ground_truth_recode","bass_default","BayesSpace_default","CellCharter_default","DRSC_default","GraphST_default","precast_default","SEDR_default","STAGATE_default"))
dfl$prediction <- factor(dfl$prediction)

selected_mt <- c("ground_truth_recode","BayesSpace_default","CellCharter_default","GraphST_default","precast_default","SEDR_default")
dfl <- dfl %>% filter(label_type %in% selected_mt)
s <- 0.2


p1 <- ggplot(dfl) +
    geom_tile(height=2, width=2, aes(x = col, y = -row, fill=ground_truth_label)) +
  geom_point(aes(x = col, y = -row, color = prediction), size = s) +
  facet_wrap(~ label_type, ncol=3) +  # Creates a separate plot for each label_type
  labs(x = "", y = "", color="Prediction", fill="Annotation") +
  theme_minimal() +
  # scale_fill_brewer(palette = "Okabe-Ito") +
  scale_color_okabe_ito(order=c(6,1,2,7,3,5,4)) +
  scale_fill_manual(values=c("0"="grey40", "1"="white")) +
  theme(
  # legend.position=c(1.08, 0.1), 
  # legend.box = "horizontal",
  legend.box.background = element_rect(fill = "grey90", color = "black", size = 0.1),
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  # legend.spacing.x = unit(-0.2, "cm"),
  axis.title.x=element_blank(),
  # legend.justification=c(1.5, 0.1),
  legend.position = "bottom",
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(-0.5, "cm"),
  panel.grid.major = element_blank(), 
  panel.grid.minor = element_blank()
) +
  guides(
    color = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3)),  # Adjust color legend key size
    fill = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3))    # Adjust size legend key size
  )
# guides(color = guide_legend(override.aes = list(size = 5)))
p1
```

```{r}
# df$ground_truth_label <- df$ground_truth_recode %>% recode("1" = "1",
#                                                            "2" = "1",
#                                                            "5" = "1",
#                                                            "3" = "1",
#                                                            "4" = "0",
#                                                            "6" = "0",
#                                                            "7" = "0")
# # plots[[4]] <- df %>%
# # ggplot() +
# # geom_point(shape=21, size=s, stroke=st, aes(x = pxl_col_in_fullres, y = pxl_row_in_fullres, fill = as.factor(SEDR_default), color = as.factor(ground_truth_label))) +
# # scale_fill_brewer(palette="Set1") +
# # theme_minimal() +
# # scale_color_manual(values=c("black", "white")) +
# # labs(x = "X", y = "Y", fill="SEDR_default", color="annotation") 
# # 
# # plots[[4]]
# 
# dfl <- pivot_longer(df, cols = contains("default") | contains("ground_truth_recode"), 
#              names_to = "label_type", values_to = "prediction") 
# dfl$label_type <- factor(dfl$label_type, levels=c("ground_truth_recode","bass_default","BayesSpace_default","CellCharter_default","DRSC_default","GraphST_default","precast_default","SEDR_default","STAGATE_default"))
# dfl$prediction <- factor(dfl$prediction)
# 
# s <- 0.8
# st <- 0.001
# 
# p1 <- ggplot(dfl, aes(x = pxl_col_in_fullres, y = pxl_row_in_fullres, fill = prediction, color = ground_truth_label)) +
# geom_point(shape=21, size = s, stroke=st) +
# facet_wrap(~ label_type, nrow=3) +  # Creates a separate plot for each label_type
# labs(x = "", y = "", fill="Prediction", color="Annotation") +
# theme_minimal() +
# # scale_fill_brewer(palette = "Okabe-Ito") +
#    scale_fill_okabe_ito(order=c(6,1,2,7,3,5,4)) +
# scale_color_manual(values=c("black", "white")) + 
#   theme(
#   # legend.position=c(1.08, 0.1), 
#   # legend.box = "horizontal",
#   legend.box.background = element_rect(fill = "grey60", color = "black", size = 0.1),
#   legend.title = element_text(size = 9),
#   legend.box.margin = margin(-1, -1, -1, -1),
#   # legend.spacing.x = unit(-0.2, "cm"),
#   axis.title.x=element_blank(),
#   # legend.justification=c(1.5, 0.1),
#   legend.position = "bottom",
#   axis.text.x=element_blank(),
#   axis.ticks.x=element_blank(),
#   axis.text.y=element_blank(),
#   axis.ticks.y=element_blank(),
#   panel.spacing.x = unit(-0.7, "cm"),
#   panel.grid.major = element_blank(), 
#   panel.grid.minor = element_blank()
# ) +
#   guides(
#     color = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3)),  # Adjust color legend key size
#     fill = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3))    # Adjust size legend key size
#   )
# # guides(color = guide_legend(override.aes = list(size = 5)))
# p1
```

```{r}
methods <- setdiff(colnames(df), c("pxl_col_in_fullres", "pxl_row_in_fullres", "label", "Row.names", "sample_id", "in_tissue", "row","col","ground_truth"))

partition_metrics <- c("RI","WC","WH","ARI","AWC","AWH", "MI","AMI","EH","EC","VM","FM", "NCR")
true <- factor(df$ground_truth)

res <- data.frame(matrix(ncol = length(partition_metrics) + 1, nrow = 0))
colnames(res) <- c("method", partition_metrics)
for (mt in methods) {
  pred <- factor(df[, mt])
  res <- rbind(res, data.frame(method=mt, getPartitionMetrics(true, pred, metrics=partition_metrics)))
}
```

```{r}
res$method <- factor(res$method)
p2 <- res %>% filter(grepl("default", method)) %>% filter(method %in% selected_mt) %>%
  pivot_longer(all_of(partition_metrics), names_to = "metric", values_to = "value") %>%
  ggplot(aes(metric, value, group=method, color=method)) +
  geom_point(size=2) + geom_line(size=0.8) +
  # scale_color_brewer(palette = "Paired") +
  scale_color_okabe_ito(order=c(6,3,2,7,1)) +
  theme_bw()
  # facet_wrap(~metric) +
  # theme(axis.text.x = element_blank())
p2
```

```{r}
partition_metrics <- c("WC","WH","AWC","AWH","FM")
true <- factor(df$ground_truth_recode)
res_class <- data.frame(matrix(ncol = 4, nrow = 0))
colnames(res_class) <- c("metric_name", "method", "class_name", "value")
for (metric in partition_metrics) {
  for (mt in methods) {
    pred <- factor(df[, mt])
    result <- getPartitionClassMetrics(true, pred, metrics=metric)
    l <- length(result[[metric]])
    res_class <- rbind(res_class, data.frame(metric_name=rep(metric, l), method=rep(mt,l), class_name = names(result[[metric]]), value = unlist(result[[metric]])))
  }
}
```

```{r}
my_col_c <- ggthemes::colorblind_pal()(8)
col_ls <- c('1' = my_col_c[7],
'2' = my_col_c[2],
'3' = my_col_c[3],
'4' = my_col_c[8],
'5' = my_col_c[4],
'6' = my_col_c[6],
'7' = my_col_c[5])
column_ha = HeatmapAnnotation(class=c("1", "2", "3", "4", "5", "6", "7"),
                              col = list(class = col_ls),  
                                  show_annotation_name = FALSE,
                                  annotation_legend_param = list(class = list(
                                ncol = 1, 
                                title = "Domains", 
                                # title_position = "topcenter",
                                # title_position = "leftcenter",
                                at = c("1", "2", "3", "4", "5", "6", "7"))),
                                show_legend = FALSE)
  
df_wide <- res_class %>% filter(metric_name %in% c("AWC") & grepl("default", method)) %>% filter(method %in% selected_mt) %>% pivot_wider(names_from = class_name, values_from = value)
mat <- as.matrix(df_wide %>% subset(select = -c(metric_name, method)))
rownames(mat) <- sub("_default", "", df_wide$method)
p3 <- mat %>%
  Heatmap(
    name = "AWC",
    bottom_annotation = column_ha)
p3 <- grid.grabExpr({
 draw(p3, merge_legend = TRUE)
})

df_wide <- res_class %>% filter(metric_name %in% c("AWH") & grepl("default", method)) %>% filter(method %in% selected_mt) %>% pivot_wider(names_from = class_name, values_from = value)
mat <- as.matrix(df_wide %>% subset(select = -c(metric_name, method)))
rownames(mat) <- sub("_default", "", df_wide$method)
p4 <- mat %>%
  Heatmap(
    name = "AWH",
    bottom_annotation = column_ha)
p4 <- grid.grabExpr({
 draw(p4, merge_legend = TRUE)
})
```

```{r}
pdf("normal_partition_metrics_spatial_real_data.pdf", width=8, height=10)
p5 <- cowplot::plot_grid(p3, p4, rel_widths=c(1,1), labels=letters[3:4], scale=c(1, 1))
cowplot::plot_grid(p1, p2, p5, ncol=1, rel_heights=c(0.6, 0.25, 0.3), labels=c("a","b", ""))
dev.off()
```


