---
title: "Spatial real data with changing k"
output: html_document
date: "2024-05-23"
---

```{r}
library(ggplot2)
library(tidyr)
library(cowplot)
library(dplyr)
library(ComplexHeatmap)
library(ggokabeito)
library(poem)
```

```{r}
df <- readRDS(file="../../data/spatial_real_data/obs_Br8100_151673_spe_coldata.RDS")
```

```{r}
true <- factor(as.integer(df$ground_truth))
clusterlabels <- factor(df$BayesSpace_default)
location <- df[,c("pxl_col_in_fullres","pxl_row_in_fullres")]

global <- data.frame(matrix(ncol = 6, nrow = 0))
colnames(global) <- c("metric","value","k")
for (k in c(6, 18, 30, 42)) {
  tmp <- getSpatialInternalMetrics(clusterlabels, location, k=k, metrics=c("PAS", "ELSA"), level="dataset")
  agg <- getSpatialExternalMetrics(true, clusterlabels, location, k=k, metrics=c("SpatialARI"), level="dataset")
  tmp <- cbind(tmp, agg)
  tmp$k <- paste0("k=",k)
  global <- rbind(global, tmp)
}
global$k <- factor(global$k, levels=c("k=6","k=18","k=30","k=42"))
```

```{r}
p0 <- global %>% pivot_longer(cols =-k, names_to="metric", values_to = "value") %>%
  # filter(metric %in% c("PAS", "ELSA","SpatialARI")) %>%
  filter(metric %in% c("PAS", "ELSA")) %>%
  ggplot(aes(k, value, group=metric, color=metric)) +
  geom_point(size=2) + geom_line(size=0.8) +
  scale_color_okabe_ito(order=c(6,3,2,7,1)) +
  theme_bw() +
  theme(
  legend.position = "bottom",
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 8), 
        legend.box.margin = margin(-1, -1, 0, -1), 
        # legend.position = c(0.5, -0.2), 
        # legend.direction = "horizontal"
        ) +
  guides(color = guide_legend(ncol = 3, keywidth = 0.8, keyheight = 0.8, override.aes = list(size = 0.8))) + labs(color="Metric")
p0
```

```{r}
res <- data.frame(matrix(ncol = 6, nrow = 0))
colnames(res) <- c("PAS", "ELSA", "ELSA.Ea", "ELSA.Ec","SpatialConcordance","k")
for (k in c(6, 18, 30, 42)) {
  tmp <- getSpatialInternalMetrics(clusterlabels, location, k=k, metrics=c("PAS", "ELSA"), level="element")
  agg <- getSpatialExternalMetrics(true, clusterlabels, location, k=k, level="element", useNegatives = FALSE, metrics=c("SpatialSPC"), fuzzy_true = TRUE, fuzzy_pred = FALSE)
  tmp$"SpatialSPC" <- agg$SpatialSPC
  agg <- getPartitionMetrics(true, clusterlabels, level="element", useNegatives = FALSE, metrics=c("SPC"))
  tmp$"SPC" <- agg$SPC
  agg <- getSpatialExternalMetrics(true, clusterlabels, location, k=k, level="element", useNegatives = TRUE, metrics=c("SpatialSPC"), fuzzy_true = TRUE, fuzzy_pred = FALSE)
  tmp$"SpatialSPC_neg" <- agg$SpatialSPC
  agg <- getPartitionMetrics(true, clusterlabels, level="element", useNegatives = TRUE, metrics=c("SPC"))
  tmp$"SPC_neg" <- agg$SPC
  tmp$k <- paste0("k=",k)
  tmp$row <- df$row
  tmp$col <- df$col
  tmp$BayesSpace <- clusterlabels
  res <- rbind(res, tmp, make.row.names=TRUE)
}

```

```{r}
dfl <- as.data.frame(res %>% pivot_longer(cols = c("PAS", "ELSA", "ELSA.Ea", "ELSA.Ec", "SpatialSPC", "SPC", "SpatialSPC_neg","SPC_neg"), names_to="metric", values_to = "value"))
dfl$k <- factor(dfl$k, levels=c("k=6","k=18","k=30","k=42"))
```


```{r}
s <- 0.3
df$ground_truth_label <- df$ground_truth_recode %>% recode("1" = "1", "2" = "1",
                                                           "5" = "1", "3" = "1",
                                                           "4" = "0", "6" = "0", "7" = "0")
p1 <- ggplot(df) +
  geom_tile(height=2, width=2, aes(x = col, y = -row, fill=ground_truth_label)) +
  geom_point(aes(x = col, y = -row, color = BayesSpace_default), size = s) +
  labs(x = "", y = "", title="BayesSpace", fill="Annotation") +
  theme_minimal() +
  scale_color_okabe_ito(order=c(6,1,2,7,3,5,4)) +
  scale_fill_manual(values=c("0"="grey40", "1"="white")) +
  theme(
  legend.box.background = element_rect(fill = "grey90", color = "black", size = 0.1),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8),  # Adjusts the font size of the legend items
  legend.box.margin = margin(-1, -1, -1, -1), 
  axis.title.x=element_blank(),
  plot.title = element_text(hjust = 0.5, margin = margin(b = -3), size=10), 
  legend.position = c(0.5, 0.04), legend.direction = "horizontal",
  axis.text.x=element_blank(), axis.ticks.x=element_blank(),
  axis.text.y=element_blank(), axis.ticks.y=element_blank(),
  panel.spacing.x = unit(-1, "cm"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  plot.margin = margin(1, -5, 0, -1)
  ) +
  guides(color="none", fill = guide_legend(keywidth = 0.3, keyheight = 0.3, nrow=1, override.aes = list(size = 0.3)))

p1
```
```{r}
st <- 0.2
p2 <- dfl %>% filter(metric == "PAS") %>% filter(k %in% c("k=6","k=18")) %>%
  mutate(value = as.logical(value)) %>%
  ggplot(aes(x = col, y = -row, color = BayesSpace)) +
  # geom_point(size=0.6, aes(shape=value), stroke = st) + 
  # geom_point(shape = 1, size = 0.6, stroke = st, aes(color=BayesSpace)) +
  geom_point(shape = 16, aes(size = value), stroke = st) +
  scale_size_manual(values=c(`TRUE`=1.5, `FALSE`=0.5)) +
  labs(x = "", y = "", color="") +
  theme_minimal() +
  facet_wrap(~k, nrow=1) +
  scale_color_okabe_ito(order=c(6,1,2,7,3,5,4)) +
  theme(
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  axis.title.x=element_blank(),
  legend.position = "right",
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(-0.1, "cm"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  plot.margin = margin(1, 1, -2, 0)
  ) +
  # scale_shape_manual(values = c(20, 8)) +
  guides(color = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3)),
         shape = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3))) +
  labs(color="BayesSpace\nPrediction", size="Abnormal\nSpots")

p2
```

```{r}
p2s <- dfl %>% filter(metric == "PAS") %>% filter(k %in% c("k=6","k=30","k=42")) %>%
  mutate(value = as.logical(value)) %>%
  ggplot(aes(x = col, y = -row, color = BayesSpace)) +
  # geom_point(size=0.6, aes(shape=value), stroke = st) + 
  # geom_point(shape = 1, size = 0.6, stroke = st, aes(color=BayesSpace)) +
  geom_point(shape = 16, aes(size = value), stroke = st) +
  scale_size_manual(values=c(`TRUE`=1.5, `FALSE`=0.5)) +
  labs(x = "", y = "", color="") +
  theme_minimal() +
  facet_wrap(~k, nrow=1) +
  scale_color_okabe_ito(order=c(6,1,2,7,3,5,4)) +
  theme(
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  axis.title.x=element_blank(),
  legend.position = "right",
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(-0.1, "cm"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  plot.margin = margin(1, 1, -2, 0)
  ) +
  # scale_shape_manual(values = c(1, 8)) +
  guides(color = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3)),
         shape = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3))) +
  labs(color="BayesSpace\nPrediction", size="Abnormal\nSpots")

p2s
```

```{r}
st <- 0.5
s <- 0.3
p3 <- dfl %>% filter(metric == "ELSA") %>% filter(k %in% c("k=6","k=18")) %>%
  ggplot(aes(x = col, y = -row, color = value)) +
  geom_point(size=s, stroke = st) + 
  labs(x = "", y = "", color="") +
  theme_minimal() +
  facet_wrap(~k, nrow=1) +
  scale_colour_gradient(low="white", high="deeppink4") +
  # scico::scale_color_scico(palette = "roma", limits = c(0, 1)) +
  theme(
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  axis.title.x=element_blank(),
  legend.position = "right",
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(0, "cm"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(), 
  plot.margin = margin(1, 1, -2, 0)
  ) +
  # scale_shape_manual(values = c(1, 8)) +
  # guides(color = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3)),
  #        shape = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3))) +
  labs(color="ELSA")

p3
```

```{r}
p3s <- dfl %>% filter(metric == "ELSA") %>% filter(k %in% c("k=6","k=30","k=42")) %>%
  ggplot(aes(x = col, y = -row, color = value)) +
  geom_point(size=s, stroke = st) + 
  labs(x = "", y = "", color="") +
  theme_minimal() +
  facet_wrap(~k, nrow=1) +
  scale_colour_gradient(low="white", high="deeppink4") +
  # scico::scale_color_scico(palette = "roma", limits = c(0, 1)) +
  theme(
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  axis.title.x=element_blank(),
  legend.position = "right",
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(0, "cm"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(), 
  plot.margin = margin(1, 1, -2, 0)
  ) +
  # scale_shape_manual(values = c(1, 8)) +
  # guides(color = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3)),
  #        shape = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3))) +
  labs(color="ELSA")

p3s
```

```{r}
st <- 0.5
p4 <- dfl %>% filter(metric == "SpatialSPC_neg") %>% filter(k %in% c("k=6","k=18")) %>%
  ggplot(aes(x = col, y = -row, color = value)) +
  geom_point(size=s, stroke = st) + 
  labs(x = "", y = "", color="") +
  theme_minimal() +
  facet_wrap(~k, nrow=1) +
  scale_colour_gradient(high="white", low="deeppink4", limits = c(0.55, 1)) +
  # scico::scale_color_scico(palette = "roma", limits = c(0, 1), direction=-1) +
  theme(
  # legend.box.background = element_rect(fill = "grey90", color = "black", size = 0.1),
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  axis.title.x=element_blank(),
  legend.position = "right",
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(0, "cm"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
    plot.margin = margin(5, 1, -2, 0),
  plot.title = element_text(hjust = 0.5, size=10, vjust=-0.2)
  ) +
  # scale_shape_manual(values = c(1, 8)) +
  # guides(color = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3)),
  #        shape = guide_legend(keywidth = 1, keyheight = 0.8, override.aes = list(size = 3))) +
  labs(color="SPC\n(use\nnegatives)", title="Spatial SPC (use negatives)")

p4
```

```{r}
p6 <- dfl %>% filter(metric == "SPC_neg") %>% filter(k == "k=6") %>%
  ggplot() +
  geom_point(aes(x = col, y = -row, color = value), size = s) +
  labs(x = "", y = "", color="") +
  theme_minimal() +
  scale_colour_gradient(high="white", low="deeppink4", limits = c(0.55, 1)) +
  # scico::scale_color_scico(palette = "roma", limits = c(0, 1), direction=-1) +
  theme(
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  axis.title.x=element_blank(),
  legend.position = "right",
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(0, "cm"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(), 
  plot.margin = margin(10, -5, -2, -5),
  plot.title = element_text(hjust = 0.5, size=10, vjust=0.2)
  ) +
  labs(color="NonSpatial\nSPC\n(use\nnegatives)", title="NonSpatial SPC\n(use negatives)")
p6
```

```{r}
max(dfl %>% filter(metric == "SpatialSPC") %>% filter(k != "k=30") %>% select(value))
```

```{r}
st <- 0.5
p8 <- dfl %>% filter(metric == "SpatialSPC") %>% filter(k %in% c("k=6","k=18")) %>%
  ggplot(aes(x = col, y = -row, color = value)) +
  geom_point(size=s, stroke = st) + 
  labs(x = "", y = "", color="") +
  theme_minimal() +
  facet_wrap(~k, nrow=1) +
  scale_colour_gradient(high="white", low="deeppink4", limits = c(0, 0.81)) +
  # scico::scale_color_scico(palette = "roma", limits = c(0, 1), direction=-1) +
  theme(
  # legend.box.background = element_rect(fill = "grey90", color = "black", size = 0.1),
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  axis.title.x=element_blank(),
  legend.position = "right",
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(0, "cm"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
    plot.margin = margin(5, 1, -2, 0),
  plot.title = element_text(hjust = 0.5, size=10, vjust=-0.2)
  ) +
  labs(color="SPC", title="Spatial SPC")

p8
```

```{r}
p9 <- dfl %>% filter(metric == "SPC") %>% filter(k == "k=6") %>%
  ggplot() +
  geom_point(aes(x = col, y = -row, color = value), size = s) +
  labs(x = "", y = "", color="") +
  theme_minimal() +
  scale_colour_gradient(high="white", low="deeppink4", limits = c(0, 0.81)) +
  # scico::scale_color_scico(palette = "roma", limits = c(0, 1), direction=-1) +
  theme(
  legend.title = element_text(size = 9),
  legend.box.margin = margin(-1, -1, -1, -1),
  axis.title.x=element_blank(),
  legend.position = "right",
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  panel.spacing.x = unit(0, "cm"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(), 
  plot.margin = margin(15, -5, -2, -5),
  plot.title = element_text(hjust = 0.5, size=10, vjust=0.2)
  ) +
  labs(color="NonSpatial\nSPC",title="NonSpatial SPC")
p9
```

```{r}
pdf("spatial_metrics_real_data.pdf", width=9.5, height=6)
p5 <- cowplot::plot_grid(p1, p2, rel_widths=c(1.5,3.2), ncol=2, labels=letters[1:2], scale=c(1, 1))

p33 <- cowplot::plot_grid(p0, 
                         p3, 
                         rel_widths=c(1.5,3.2), ncol=2, labels=c("c","d"), scale=c(1, 1))

cowplot::plot_grid(p5, p33, rel_heights=c(1,1), ncol=1, labels=c("",""), scale=c(1, 1))
dev.off()
```

```{r}
pdf("spatial_metrics_real_data_suppl.pdf", width=9.5, height=6)
cowplot::plot_grid(p2s, p3s, rel_widths=c(1,1), nrow=2, labels=letters[1:2], scale=c(1, 1))
dev.off()
```




```{r}
# Create an empty plot
empty_plot <- ggdraw() 

p7 <- cowplot::plot_grid(empty_plot, p6, p9, 
                         rel_widths=c(1.3,1,1), ncol=3, 
                         labels=c("a","b","c"))

# p7 <- cowplot::plot_grid(p6, p4, 
#                          rel_widths=c(1,2.4), ncol=2, 
#                          labels=c("b","c"), scale=c(1, 1))

p10 <- cowplot::plot_grid(p4, p8, 
                         rel_widths=c(1,1), ncol=2, 
                         labels=c("d","e"), scale=c(1, 1))

# pn <- cowplot::plot_grid(p7, p10, nrow=2, 
#                    labels=c("",""))

empty_plot <- ggdraw() 

pdf("spatial_metrics_real_data_spc.pdf", width=9.5, height=5)
cowplot::plot_grid(p7, p10,
                   rel_widths=c(1,1), nrow=2, 
                   labels=c("",""))

dev.off()
```


