---
title: "Silhouette width and distance metric on LSI embedding of scATAC"
author: "Pierre-Luc Germain"
output: workflowr::wflow_html
editor_options: 
  chunk_output_type: console
---

```{r setup}
knitr::opts_chunk$set(dev="CairoPNG")
suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
  library(cowplot)
})
```

```{r}
d <- readRDS("../../data/silhouette_real_life_examples/Atlas2_ArchR_tiles_ndim15_LSI.rds")
levels(d$class) <- gsub("_","\n",gsub("_[0-9]|_Type","",levels(d$class)))
```

```{r}
x <- d[,paste0("LSI_", 1:15)]
labels <- d$class

closest_centroid <- function(embedding, labels, method = c("euclidean", "cosine")) {
  method <- match.arg(method)
  embedding <- as.matrix(embedding)
  labels <- as.factor(labels)
  
  # Compute centroids
  centroids <- t(sapply(levels(labels), function(class) {
    colMeans(embedding[labels == class, ])
  }))
  rownames(centroids) <- levels(labels)
  
  # Normalize if using cosine distance
  if (method == "cosine") {
    distances <- proxy::dist(embedding, centroids, method = "cosine")
  } else if (method == "euclidean") {
      distances <- proxy::dist(embedding, centroids, method = "euclidean")
  } else {stop("Unknown method")}
  # Find closest class
  closest_indices <- apply(distances, 1, which.min)
  closest_classes <- levels(labels)[closest_indices]
  
  return(closest_classes)
}

res <- closest_centroid(x, labels, method = "cosine")

sil.euclidean <- as.data.frame(cluster::silhouette(as.numeric(labels), dist(x, method="euclidean")))
sil.euclidean <- sil.euclidean %>% mutate(closest=ifelse(sil_width > 0, cluster, neighbor))
d$closest.euclidean <- levels(labels)[sil.euclidean$closest]
d$closest.cosine <- res
```

```{r, fig.width=8, fig.height=5}
d2 <- data.frame(cell=c(rownames(d), rownames(d)),
                 class=rep(d$class,2), silhW=c(d$silhW, d$cosSilhW), 
                 type=rep(factor(c("Euclidean","Cosine"),c("Euclidean","Cosine")), each=nrow(d)),
                 closest=c(as.character(d$closest.euclidean), as.character(d$closest.cosine)))
d2$closest <- d2$closest %>% factor(levels=levels(d$class))
d2 <- d2[order(d2$type,d2$class,d2$silhW),]
d2$rank <- rep(seq_len(nrow(d)),2)

# psw1 <- ggplot(d2, aes(y=rank, xmin=0, xmax=silhW, fill=class, group=class)) + geom_ribbon() + 
#   facet_wrap(~type, scales="free_y") + coord_cartesian(ylim=c(-100,max(d2$rank)+100), expand=FALSE) +
#   theme_bw() + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank()) +
#   labs(y="Cells", x="Silhouette width") + guides(fill=guide_legend(ncol=2))
# leg <- cowplot::get_legend(psw)

# psw1 <- ggplot(d2, aes(x=rank, y=silhW, fill=class, group=class)) + geom_bar(stat = "identity", width = 1) + 
#   facet_wrap(~type, scales="free_y") + 
#   coord_cartesian(xlim=c(-100,max(d2$rank)+100), expand=FALSE) +
#   theme_bw() + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), 
#                      axis.text.y=element_blank(), axis.ticks.y=element_blank()) +
#   labs(x="", y="Silhouette width") + guides(fill=guide_legend(ncol=2)) + 
#   coord_flip()
# leg <- cowplot::get_legend(psw)
# 
# psw2 <- ggplot(d2, aes(x=rank, y=silhW, fill=closest, group=class)) + geom_bar(stat = "identity", width = 1) + 
#   facet_wrap(~type, scales="free_y") + 
#   coord_cartesian(xlim=c(-100,max(d2$rank)+100), expand=FALSE) +
#   theme_bw() + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),
#                      axis.text.y=element_blank(), axis.ticks.y=element_blank()) +
#   labs(x="", y="Silhouette width") + guides(fill=guide_legend(ncol=2)) + 
#   coord_flip()

class_labels <- levels(labels)
names(class_labels)  <- levels(labels)
class_labels[1] <- "Alveolar Cell"
class_labels[3] <- "Ductal Cell Pan."
class_labels[6] <- "Periph. N. Stromal"
class_labels[7] <- "Parietal Cell"

psw <- ggplot(d2, aes(x=-rank, y=silhW, fill=closest, group=class)) + 
  geom_bar(stat = "identity", width = 1) + 
    facet_grid(type~class, scales = "free_x", space = "free",
               labeller = labeller(class = class_labels)) + 
  coord_cartesian(expand=FALSE) + 
  # coord_flip() + 
    theme_bw() + 
    labs(x="", y="Silhouette width") +
  theme(legend.position="none", 
        panel.border = element_rect(fill = NA), 
        panel.spacing = unit(0, "lines"),
        panel.grid = element_blank(),
        axis.text.x=element_blank(), 
        axis.ticks.x=element_blank(),
        strip.text.x = element_text(size = 8, angle = 90), 
        strip.text.y = element_text(size = 8, angle = 90)
        )

# psw <- ggplot(d2, aes(silhW, class, fill=class)) + geom_vline(xintercept=0) + 
#   geom_violin() + stat_summary() + facet_wrap(~type) + labs(x="Silhouette widths") +
#   theme_bw() + theme(legend.position = "none", axis.title.y=element_blank())

umap <- ggplot(d, aes(UMAP_1,UMAP_2,colour=class)) + ggrastr::geom_point_rast(size=0.3) + theme_bw() + 
  theme(panel.grid=element_blank(), panel.border=element_blank(), legend.position = "none",
        axis.text=element_blank(), axis.ticks=element_blank(), axis.line=element_line())
  # guides(colour = guide_legend(nrow = 3, title = element_blank(), override.aes = list(size=4)))
```


```{r, fig.height=7, fig.width=8}
p0 <- ggplot(d, aes(LSI_4, LSI_5, colour=class)) + geom_point(alpha=0.3, size=0.3) + theme_bw()
an <- data.frame(LSI_4=c(-8,-3), LSI_5=c(-25,-10))
p1 <- ggplot(d[order(-d$log10sum),], aes(LSI_4, LSI_5, colour=log10sum)) + geom_point() + theme_bw() + scale_colour_viridis_c() +
    labs(colour="log10 total\ncounts") + geom_line(data=an, colour="black", linetype="dashed") +
    geom_point(data=an, colour="black", shape="+", size=7) +
  annotate("text", x=-2, y=-27, label="Large within-class distances\ndue to library size differences", hjust=0, size=3)
  # theme(legend.position="bottom")

d <- d[order(d$class, d$silhW),]
d$class2 <- gsub("_","\n",gsub("_[1-2]","",d$class))
# d$cell <- factor(row.names(d), row.names(d))
# ps <- ggplot(d, aes(cell, silhW, group=class, fill=class)) + geom_col(position="dodge") + 
#   labs(x="Cells", y="Silhouette width") + 
#   theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

# ps <- ggplot(d, aes(class2, silhW, fill=class2)) + geom_hline(yintercept=0, linetype="dashed") +
#   geom_violin() + labs(x="Cell classes", y="Silhouette width") + theme_bw() + theme(legend.position="none")

pb <- ggplot(d[order(-d$silhW),], aes(LSI_4, LSI_5, colour=silhW)) + geom_point() + theme_bw() + scale_color_gradient2(breaks=c(-0.5,0,0.5)) + 
  labs(colour="Silhouette\nwidth") #+ theme(legend.position="bottom")
```


```{r, fig.height=9, fig.width=8.5}
pdf("LSI_Silh.pdf", width=8.5, height=9)
plot_grid(plot_grid(umap, psw + theme(legend.position = "none"), nrow=1, labels="auto", rel_widths=c(2, 3.5)),
          plot_grid(p0 + theme(legend.position = "none") + geom_density2d(color="black", size=0.2), leg, labels=c("c",NA), rel_widths = c(5,2)),
          plot_grid(p1,pb,nrow=1,labels=letters[4:5]), nrow=3, scale=0.95, rel_heights = c(4,3,3))
dev.off()
```


