LABEL_FILE: "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/subsampled.RDS"
OUT_DIR: "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/scalability_benchmark/"
EMBED_DIR: "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/"
NDIM_EMBED: 10
# SIZE_ID: [1,2,3,4]
SIZE_ID: [1,2,3,4]
METRIC:
  - name: "AMSP"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5": "cluster_5"
      "11": "cluster_11"
      "14": "cluster_14"
    pred: 
      "5":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_5/embedding.tsv"
      "11":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_11/embedding.tsv"
      "14":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_14/embedding.tsv"
  - name: "NCE"
    args_id: "default"
    args: ""
    level: "dataset"
    truth:
      "5":  "cluster_5"
      "11":  "cluster_11"
      "14":  "cluster_14"
    pred: 
      "5":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_5/embedding.tsv"
      "11":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_11/embedding.tsv"
      "14":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_14/embedding.tsv"
  - name: "NP"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "cluster_5"
      "11":  "cluster_11"
      "14":  "cluster_14"
    pred: 
      "5":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_5/embedding.tsv"
      "11":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_11/embedding.tsv"
      "14":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_14/embedding.tsv"
  - name: "PWC"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "cluster_5"
      "11":  "cluster_11"
      "14":  "cluster_14"
    pred: 
      "5":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_5/embedding.tsv"
      "11":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_11/embedding.tsv"
      "14":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_14/embedding.tsv"
  - name: "cohesion"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "cluster_5"
      "11":  "cluster_11"
      "14":  "cluster_14"
    pred: 
      "5":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_5/embedding.tsv"
      "11":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_11/embedding.tsv"
      "14":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_14/embedding.tsv"
  - name: "cdbw"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "cluster_5"
      "11":  "cluster_11"
      "14":  "cluster_14"
    pred: 
      "5":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_5/embedding.tsv"
      "11":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_11/embedding.tsv"
      "14":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_14/embedding.tsv"
  - name: "dbcv"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "cluster_5"
      "11":  "cluster_11"
      "14":  "cluster_14"
    pred: 
      "5":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_5/embedding.tsv"
      "11":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_11/embedding.tsv"
      "14":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_14/embedding.tsv"
  - name: "meanSW"  # it uses the implementation in the package cluster
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "cluster_5"
      "11":  "cluster_11"
      "14":  "cluster_14"
    pred: 
      "5":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_5/embedding.tsv"
      "11":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_11/embedding.tsv"
      "14":  "/cluster/work/nme/data/siluo/metrics_benchmark/visium_hd_cancer_colon_square_016um_small/CellCharter/CellCharter/config_default/cluster_14/embedding.tsv"
  - name: "ARI"
    args_id: "default"
    args: ""
    level: "dataset"
    truth:
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11"
      "14":  "cluster_14"
  - name: "ASPC"
    args_id: "useNegativesF"
    args: "useNegatives=FALSE"
    level: "element"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "SPC"
    args_id: "default"
    args: ""
    level: "element"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "AWC"
    args_id: "default"
    args: ""
    level: "class"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "AWH" 
    args_id: "default"
    args: ""
    level: "class"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "NCR"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"

  - name: "SpatialARI"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "SpatialRI"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "SpatialSPC"
    args_id: "default"
    args: ""
    level: "element"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "SpatialAccuracy"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "nsARI"
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "nsARI"
    args_id: "lowMemoryT"
    args: "lowMemory=TRUE"
    level: "dataset"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "nsARI"
    args_id: "lowMemoryF"
    args: "lowMemory=FALSE"
    level: "dataset"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "nsAWC"
    args_id: "default"
    args: ""
    level: "class"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "nsAWC"
    args_id: "lowMemoryT"
    args: "lowMemory=TRUE"
    level: "class"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "nsAWC"
    args_id: "lowMemoryF"
    args: "lowMemory=FALSE"
    level: "class"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "nsAWH"
    args_id: "default"
    args: ""
    level: "class"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "nsAWH"
    args_id: "lowMemoryT"
    args: "lowMemory=TRUE"
    level: "class"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "nsAWH"
    args_id: "lowMemoryF"
    args: "lowMemory=FALSE"
    level: "class"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "nsSPC" 
    args_id: "default"
    args: ""
    level: "element"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
  - name: "SpatialARI_Yan" 
    args_id: "default"
    args: ""
    level: "dataset"
    truth: 
      "5":  "label"
      "11":  "label"
      "14":  "label"
    pred_col: 
      "5":  "cluster_5"
      "11":  "cluster_11" 
      "14":  "cluster_14"
